import PropTypes from 'prop-types';

export const propTypes = {
  title: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.node,
  ]),
  selectableRows: PropTypes.bool,
  selectableRowsHighlight: PropTypes.bool,
  selectableRowsVisibleOnly: PropTypes.bool,
  selectableRowSelected: PropTypes.func,
  onRowsSelectedUpdate: PropTypes.func,
  clearSelectedRows: PropTypes.bool,
  keyField: PropTypes.string,
  persistTableHead: PropTypes.bool,
  noContextMenu: PropTypes.bool,
  defaultSortField: PropTypes.string,
  defaultSortAsc: PropTypes.bool,
  columns: PropTypes.array,
  data: PropTypes.array,
  className: PropTypes.string,
  style: PropTypes.object,
  responsive: PropTypes.bool,
  overflowY: PropTypes.bool,
  overflowYOffset: PropTypes.string,
  onRowClick: PropTypes.func,
  noDataComponent: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.node,
    PropTypes.func,
  ]),
  disabled: PropTypes.bool,
  fixedHeader: PropTypes.bool,
  fixedHeaderScrollHeight: PropTypes.string,
  theme: PropTypes.string,
};

export const defaultProps = {
  title: '',
  keyField: 'id',
  selectableRows: false,
  selectableRowsHighlight: false,
  selectableRowSelected: null,
  clearSelectedRows: false,
  isLoading: false,
  persistTableHead: false,
  sortIcon: false,
  defaultSortField: null,
  defaultSortAsc: true,
  columns: [],
  data: [],
  onRowClick: () => null,
  className: null,
  style: {},
  responsive: true,
  overflowY: false,
  overflowYOffset: '250px',
  disabled: false,
  fixedHeader: false,
  fixedHeaderScrollHeight: '100vh',
  conditionalRowStyles: [],
  theme: 'default',
};
